# Generated by Django 3.2.5 on 2021-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOCIALaCCOUNTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.CharField(max_length=200)),
                ('Twitter', models.CharField(max_length=200)),
                ('Instagram', models.CharField(max_length=200)),
                ('YouTube', models.CharField(max_length=200)),
                ('LinkedIn', models.CharField(max_length=200)),
            ],
        ),
    ]
