# Generated by Django 3.2.5 on 2021-07-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SINGER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=255)),
                ('S_Gender', models.CharField(max_length=255)),
                ('S_Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Song_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DATABASEmODELS.singer')),
            ],
        ),
    ]
